//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorkDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullGoogleDork
    {
        public Nullable<System.DateTime> DiscoveryDate { get; set; }
        public string Summary { get; set; }
        public int GoogleDorkParentId { get; set; }
        public string GoogleDorkParentName { get; set; }
        public string GoogleUrl { get; set; }
        public string GhdbUrl { get; set; }
        public int GoogleDorkId { get; set; }
    }
}
