//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorkDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleDorkParent
    {
        public GoogleDorkParent()
        {
            this.GoogleDorks = new HashSet<GoogleDork>();
        }
    
        public string Name { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<GoogleDork> GoogleDorks { get; set; }
    }
}
