//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorkWeb.DorkServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoogleDorkParent", Namespace="http://schemas.datacontract.org/2004/07/DorkServices.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GoogleDorkParent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDork> GoogleDorksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDork> GoogleDorks {
            get {
                return this.GoogleDorksField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleDorksField, value) != true)) {
                    this.GoogleDorksField = value;
                    this.RaisePropertyChanged("GoogleDorks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoogleDork", Namespace="http://schemas.datacontract.org/2004/07/DorkServices.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GoogleDork : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DiscoveryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GhdbUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoogleDorkParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoogleUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DiscoveryDate {
            get {
                return this.DiscoveryDateField;
            }
            set {
                if ((this.DiscoveryDateField.Equals(value) != true)) {
                    this.DiscoveryDateField = value;
                    this.RaisePropertyChanged("DiscoveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GhdbUrl {
            get {
                return this.GhdbUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.GhdbUrlField, value) != true)) {
                    this.GhdbUrlField = value;
                    this.RaisePropertyChanged("GhdbUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoogleDorkParentId {
            get {
                return this.GoogleDorkParentIdField;
            }
            set {
                if ((this.GoogleDorkParentIdField.Equals(value) != true)) {
                    this.GoogleDorkParentIdField = value;
                    this.RaisePropertyChanged("GoogleDorkParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleUrl {
            get {
                return this.GoogleUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleUrlField, value) != true)) {
                    this.GoogleUrlField = value;
                    this.RaisePropertyChanged("GoogleUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoogleDorkParentSort", Namespace="http://schemas.datacontract.org/2004/07/DorkServices.DataContracts")]
    public enum GoogleDorkParentSort : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Id = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Name = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DorkServiceReference.IDorkService")]
    public interface IDorkService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDorkService/GetGoogleDorks", ReplyAction="http://tempuri.org/IDorkService/GetGoogleDorksResponse")]
        System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent> GetGoogleDorks(string site);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDorkService/GetGoogleDorks", ReplyAction="http://tempuri.org/IDorkService/GetGoogleDorksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent>> GetGoogleDorksAsync(string site);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDorkService/SearchGoogleDorks", ReplyAction="http://tempuri.org/IDorkService/SearchGoogleDorksResponse")]
        System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent> SearchGoogleDorks(string site, string keywords, System.Collections.Generic.List<int> googleDorkParentIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDorkService/SearchGoogleDorks", ReplyAction="http://tempuri.org/IDorkService/SearchGoogleDorksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent>> SearchGoogleDorksAsync(string site, string keywords, System.Collections.Generic.List<int> googleDorkParentIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDorkService/GetGoogleDorkParents", ReplyAction="http://tempuri.org/IDorkService/GetGoogleDorkParentsResponse")]
        System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent> GetGoogleDorkParents(DorkWeb.DorkServiceReference.GoogleDorkParentSort googleDorkParentSort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDorkService/GetGoogleDorkParents", ReplyAction="http://tempuri.org/IDorkService/GetGoogleDorkParentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent>> GetGoogleDorkParentsAsync(DorkWeb.DorkServiceReference.GoogleDorkParentSort googleDorkParentSort);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDorkServiceChannel : DorkWeb.DorkServiceReference.IDorkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DorkServiceClient : System.ServiceModel.ClientBase<DorkWeb.DorkServiceReference.IDorkService>, DorkWeb.DorkServiceReference.IDorkService {
        
        public DorkServiceClient() {
        }
        
        public DorkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DorkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DorkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DorkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent> GetGoogleDorks(string site) {
            return base.Channel.GetGoogleDorks(site);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent>> GetGoogleDorksAsync(string site) {
            return base.Channel.GetGoogleDorksAsync(site);
        }
        
        public System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent> SearchGoogleDorks(string site, string keywords, System.Collections.Generic.List<int> googleDorkParentIds) {
            return base.Channel.SearchGoogleDorks(site, keywords, googleDorkParentIds);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent>> SearchGoogleDorksAsync(string site, string keywords, System.Collections.Generic.List<int> googleDorkParentIds) {
            return base.Channel.SearchGoogleDorksAsync(site, keywords, googleDorkParentIds);
        }
        
        public System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent> GetGoogleDorkParents(DorkWeb.DorkServiceReference.GoogleDorkParentSort googleDorkParentSort) {
            return base.Channel.GetGoogleDorkParents(googleDorkParentSort);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DorkWeb.DorkServiceReference.GoogleDorkParent>> GetGoogleDorkParentsAsync(DorkWeb.DorkServiceReference.GoogleDorkParentSort googleDorkParentSort) {
            return base.Channel.GetGoogleDorkParentsAsync(googleDorkParentSort);
        }
    }
}
